language: python
python:
  - 3.6
  - 3.7
  - 3.8
os:
  - linux
  - osx
  - windows
install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f conda.yml python=$TRAVIS_PYTHON_VERSION
  - conda activate pst
  - pip install -e .
  - pip install pytest
  - cd tests
  - pytest
