nqn: 4                        # number of quantum numbers
min_N: 0                      # minimum value for N
max_N: 2                      # maximum value for N
min_hfs:  0                   # minimum value for F quantum numbers
max_hfs: 10                   # maximum value for F quantum numbers
frequencies:                  # list of frequencies for fitting
  - 30251.321
  - 30265.621
  - 30278.516
mode: "brute"                 # mode used for the autofitting
fixed:                        # dictionary of fixed transitions
  0:                          # keys correspond to the line index
    N: [1, 0]                 # with values corresponding to the
    F: [2, 1]                 # dictionary containing the specifications
